feat: add Celestia testnet Big Dipper [web-celestia]
forbole/big-dipper-2.0-cosmos pull request #1233
Opened 2023-05-02 08:42 UTC by rachelhox

## Description

Closes: [BDU-918](https://forbole.atlassian.net/browse/BDU-918)

---

### Author Checklist

_All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues._

I have...

- [ ] ran linting via `yarn lint`
- [ ] wrote tests where necessary
- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed
- [ ] added a changeset via [`yarn && yarn changeset`](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md)

2023-05-03 10:34 UTC, rachelhox commented
@teamchong will integrate this to home page for celestia too if everything looks good, so far this custom profile hook is applied on `/validators` page only

2023-05-04 03:39 UTC, teamchong approved these changes
LGTM

2023-05-04 12:33 UTC, MonikaCat approved these changes
LGTM

2023-05-04 12:36 UTC, MonikaCat commented
@rachelhox can you also add the hook to home page before merging pls? Thanks!

2023-05-04 12:41 UTC, MonikaCat requested changes
Can you also update the validator profile page? Some validators name and avatar doesn't show [like this one](https://cosmos-odijiusz3-bigdipper.vercel.app/validators/celestiavaloper1wsyjvdx6ymjxtt8pv6ut0t4fx8jlg5v9pls30a)

2023-05-04 20:44 UTC, teamchong commented on apps/web-celestia/src/hooks/use_celestia_profile/index.ts
Hi @rachelhox,

Could we use `useCelestiaProfile` instead of `use_celestia_profile` to align with our code style? Also, could we export useCelestiaProfile as the default at the end of the file?

Let me know if you have any concerns or questions about these changes.

2023-05-05 10:05 UTC, MonikaCat approved these changes

2023-05-05 10:12 UTC, teamchong approved these changes

2023-05-05 10:13 UTC, merged