460/bit song/nft tx
forbole/big-dipper-2.0-cosmos pull request #463
Opened 2021-10-15 05:23 UTC by yayay927

closes #460 

## Description

## Checklist
- [ ] Ran Linting
- [ ] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [ ] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-10-18 01:44 UTC, ryuash requested changes

2021-10-18 01:44 UTC, ryuash commented on public/locales/en/message_contents.json
> +  "txIssueDenomContent": "<0>{{creators}}</0> issued NFT <1>{{name}}</1> for <2>{{split_shares}}</2>",
```
// MsgIssueDenom defines an SDK message for creating a new denom.
type MsgIssueDenom struct {
	Id           string                                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Creators     []string                                 `protobuf:"bytes,3,rep,name=creators,proto3" json:"creators,omitempty"`
	SplitShares  []github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,rep,name=split_shares,json=splitShares,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"split_shares" yaml:"split_shares"`
	RoyaltyShare github_com_cosmos_cosmos_sdk_types.Dec   `protobuf:"bytes,5,opt,name=royalty_share,json=royaltyShare,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"royalty_share" yaml:"royalty_share"`
	Sender       string                                   `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
}
```

I don't think this has anything to do with NFT. It's just creating a new denom

2021-10-18 01:44 UTC, ryuash commented on src/models/msg/nft/msg_issue_denom.ts
> +  public royaltyShare: MsgCoin;
I don't think the type is `MsgCoin`

```
// NOTE: never use new(Dec) or else we will panic unmarshalling into the
// nil embedded big.Int
type Dec struct {
	i *big.Int
}
```

---

We don't need to log the whole model. Just whatever the tx message needs

2021-10-20 12:34 UTC, ryuash commented on i18n.js
> +    '*': ['common', 'message_labels', 'message_contents', 'transactions'],
```
'*': ['common']
```

2021-10-20 12:40 UTC, ryuash commented on src/components/msg/nft/transfer_nft/index.tsx
> +        ]}
```
"txTransferNFTContent": "<0>{{sender}}</0> sent NFT <1>{{id}}</1> to <2>{{recipient}}</2>",
```

there only 3 variables here why is there 4 in this component

2021-10-20 12:40 UTC, ryuash commented on src/components/msg/utils.tsx
> +
Where are the other ones?

2021-10-21 01:59 UTC, yayay927 commented on src/components/msg/utils.tsx
> +
Add now.

2021-10-21 03:38 UTC, merged