add: tombstoned status
forbole/big-dipper-2.0-cosmos pull request #601
Opened 2021-12-13 07:22 UTC by ryuash

## Description

closes #600 

## Checklist
- [ ] Ran Linting
- [ ] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [ ] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-12-13 07:56 UTC, ryuash commented
update: check the tombstone and jailed status before 1,2,3. 
You can be tombstoned and unbonding at the same time

2021-12-14 04:01 UTC, yayay927 commented on src/screens/account_details/components/staking/components/delegations/components/desktop/index.tsx
> +    const statusTheme = getValidatorStatus(
Please update test.

2021-12-14 04:02 UTC, yayay927 requested changes

2021-12-14 04:02 UTC, yayay927 commented on src/screens/account_details/components/staking/components/delegations/components/desktop/index.tsx
> +      x.validatorSigningInfo.tombstoned,
Please update test.

2021-12-14 04:02 UTC, yayay927 commented on src/screens/account_details/components/staking/components/delegations/components/mobile/index.tsx
> +        );
Same for this one.

2021-12-14 06:35 UTC, yayay927 requested changes

2021-12-14 06:35 UTC, yayay927 commented on src/screens/validators/components/list/components/desktop/index.tsx
> +    const status = getValidatorStatus(x.status, x.jailed, x.tombstoned);
Please update test.

2021-12-14 06:35 UTC, yayay927 commented on src/screens/validators/components/list/components/mobile/index.tsx
> +    const status = getValidatorStatus(x.status, x.jailed, x.tombstoned);
Same for this one.

2021-12-14 06:56 UTC, yayay927 approved these changes

2021-12-14 07:14 UTC, merged