Bdu 62 add quorum back in to proposal details
forbole/big-dipper-2.0-cosmos pull request #809
Opened 2022-04-06 19:11 UTC by yayay927

closes #788 

## Description

## Checklist
- [ ] Ran Linting
- [ ] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [ ] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2022-04-08 02:09 UTC, ryuash requested changes
Please fix mobile and tablet view

<img width="325" alt="image" src="https://user-images.githubusercontent.com/42913823/162349240-cb660cf0-6bf8-47c1-88f8-53869fba756d.png">

2022-04-08 02:09 UTC, ryuash commented on src/screens/proposal_details/components/votes_graph/hooks.tsx
> +      quorum: numeral(numeral(quorumRaw).format('0.[00]')).value() * 100,
Maybe:

```
quorum: Big(quorumRaw).times(100).toFixed(2)
```

2022-04-08 02:10 UTC, ryuash commented on src/screens/proposal_details/components/votes_graph/components/quorum_explanation/index.tsx
> +const QuorumExplanation = (props) => {
props should not be `any`

2022-04-08 18:37 UTC, yayay927 commented on src/screens/proposal_details/components/votes_graph/components/quorum_explanation/index.tsx
> +const QuorumExplanation = (props) => {
updated

2022-04-08 18:37 UTC, yayay927 commented on src/screens/proposal_details/components/votes_graph/hooks.tsx
> +      quorum: numeral(numeral(quorumRaw).format('0.[00]')).value() * 100,
updated

2022-04-09 13:03 UTC, ryuash requested changes
There is an overflow in desktop now
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/42913823/162575312-05814310-292c-4e55-9665-2ba54f495dee.png">

2022-04-11 19:16 UTC, merged