fix: div by zero error
forbole/big-dipper-2.0-cosmos pull request #997
Opened 2022-09-08 08:57 UTC by teamchong

Fixed divide by zero error on market recoil state

## Checklist
- [X] Ran Linting
- [ X Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [ ] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2022-09-11 15:56 UTC, yayay927 requested changes
The logo size seems abnormal (much bigger) from what we usually have. Can you double check? And can you also double check with backend about the 6 months delayed data?
<img width="1440" alt="截圖 2022-09-11 下午11 44 43" src="https://user-images.githubusercontent.com/32444273/189537029-cdbfa2ff-d067-4926-b0c1-c78b4521858d.png">

2022-09-11 22:50 UTC, teamchong commented
> The logo size seems abnormal (much bigger) from what we usually have for previous BDs. Can you double check? And can you also double check with backend about the 6 months delayed data? <img alt="截圖 2022-09-11 下午11 44 43" width="1440" src="https://user-images.githubusercontent.com/32444273/189537029-cdbfa2ff-d067-4926-b0c1-c78b4521858d.png">

thanks! I will address this in another PR

2022-09-13 19:42 UTC, yayay927 requested changes

2022-09-13 19:42 UTC, yayay927 commented on CHANGELOG_PERSISTENCE.md
> +- Fixed divide by zero error on market recoil state
@teamchong please add the issue link

2022-09-13 19:48 UTC, yayay927 requested changes
@teamchong I've merged pr #1001 , please pull the latest branch change and push again. Thx

2022-09-14 18:22 UTC, merged